github: [chris-short]
patreon: devopsish
custom: ["paypal.me/devopsish", devopsish.com, chrisshort.net, kubernetesreadme.com, kubenews.net, devopsreadme.com, devopsnewsletters.com, nomedium.dev, crashloopbackoff.dev]